//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public System.DateTime FechaPago { get; set; }
        public Nullable<double> MontoPago { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public Nullable<int> IdMora { get; set; }
        public int IdPago { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<int> ModificaPor { get; set; }
        public Nullable<int> EliminaPor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Mora Mora { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
